package com.db.oliviergoutay.greendao_vs_realm.schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEAL_PHOTO".
 */
public class MealPhoto {

    private Long id;
    private String filename;
    private String downloadUrl;
    private String photoType;

    public MealPhoto() {
    }

    public MealPhoto(Long id) {
        this.id = id;
    }

    public MealPhoto(Long id, String filename, String downloadUrl, String photoType) {
        this.id = id;
        this.filename = filename;
        this.downloadUrl = downloadUrl;
        this.photoType = photoType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public String getPhotoType() {
        return photoType;
    }

    public void setPhotoType(String photoType) {
        this.photoType = photoType;
    }

}
